# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character]      # The name of the module we are configuring is "character"
# symbol = "ğŸ ¦"     # The "symbol" segment is being set to "âœ"
# symbol = "âœ"     # The "symbol" segment is being set to "âœ"
# symbol = "ã€°ï¸"
# symbol = "â§"
# symbol = "â†’"
success_symbol = "[â—Š](bold green)" 
error_symbol = "[â—Š](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[golang]
symbol = "go "
